// src-tauri/src/services/blueprint_catalog.rs
// Pre-compiled zero-copyright 5e SRD entity blueprints, detection keywords, and canonical IDs.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AbilityScores {
    pub str: i32,
    pub dex: i32,
    pub con: i32,
    pub int: i32,
    pub wis: i32,
    pub cha: i32,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct EntityBlueprint {
    pub id: &'static str,
    pub name: &'static str,
    pub category: &'static str, // "monster" | "spell" | "magic_item"
    pub keywords: &'static [&'static str],
    pub default_cr: Option<&'static str>,
    pub ac: Option<i32>,
    pub hp: Option<i32>,
    pub speed: Option<&'static str>,
    pub stats: Option<AbilityScores>,
    pub attack_bonus: Option<i32>,
    pub damage_formula: Option<&'static str>,
}

/// Static compile-time blueprint catalog containing pure 5e SRD mechanical specifications.
/// Contains ZERO copyrighted lore, narrative descriptions, or non-SRD trademarks.
pub static BLUEPRINT_CATALOG: &[EntityBlueprint] = &[
    // ── Monsters ─────────────────────────────────────────────────────────────
    EntityBlueprint {
        id: "srd_goblin",
        name: "Goblin",
        category: "monster",
        keywords: &["Goblin", "Small humanoid (goblinoid)"],
        default_cr: Some("1/4"),
        ac: Some(15),
        hp: Some(7),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 8,
            dex: 14,
            con: 10,
            int: 10,
            wis: 8,
            cha: 8,
        }),
        attack_bonus: Some(4),
        damage_formula: Some("1d6 + 2"),
    },
    EntityBlueprint {
        id: "srd_kobold",
        name: "Kobold",
        category: "monster",
        keywords: &["Kobold", "Small humanoid (kobold)"],
        default_cr: Some("1/8"),
        ac: Some(12),
        hp: Some(5),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 7,
            dex: 15,
            con: 9,
            int: 8,
            wis: 7,
            cha: 8,
        }),
        attack_bonus: Some(4),
        damage_formula: Some("1d4 + 2"),
    },
    EntityBlueprint {
        id: "srd_orc",
        name: "Orc",
        category: "monster",
        keywords: &["Orc", "Medium humanoid (orc)"],
        default_cr: Some("1/2"),
        ac: Some(13),
        hp: Some(15),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 16,
            dex: 12,
            con: 16,
            int: 7,
            wis: 11,
            cha: 10,
        }),
        attack_bonus: Some(5),
        damage_formula: Some("1d12 + 3"),
    },
    EntityBlueprint {
        id: "srd_skeleton",
        name: "Skeleton",
        category: "monster",
        keywords: &["Skeleton", "Medium undead"],
        default_cr: Some("1/4"),
        ac: Some(13),
        hp: Some(13),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 10,
            dex: 14,
            con: 15,
            int: 6,
            wis: 8,
            cha: 5,
        }),
        attack_bonus: Some(4),
        damage_formula: Some("1d6 + 2"),
    },
    EntityBlueprint {
        id: "srd_zombie",
        name: "Zombie",
        category: "monster",
        keywords: &["Zombie", "Medium undead"],
        default_cr: Some("1/4"),
        ac: Some(8),
        hp: Some(22),
        speed: Some("20 ft."),
        stats: Some(AbilityScores {
            str: 13,
            dex: 6,
            con: 16,
            int: 3,
            wis: 6,
            cha: 5,
        }),
        attack_bonus: Some(3),
        damage_formula: Some("1d6 + 1"),
    },
    EntityBlueprint {
        id: "srd_bugbear",
        name: "Bugbear",
        category: "monster",
        keywords: &["Bugbear", "Medium humanoid (goblinoid)"],
        default_cr: Some("1"),
        ac: Some(16),
        hp: Some(27),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 15,
            dex: 14,
            con: 13,
            int: 8,
            wis: 11,
            cha: 9,
        }),
        attack_bonus: Some(4),
        damage_formula: Some("2d8 + 2"),
    },
    EntityBlueprint {
        id: "srd_ghoul",
        name: "Ghoul",
        category: "monster",
        keywords: &["Ghoul", "Medium undead"],
        default_cr: Some("1"),
        ac: Some(12),
        hp: Some(22),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 13,
            dex: 15,
            con: 10,
            int: 7,
            wis: 10,
            cha: 6,
        }),
        attack_bonus: Some(4),
        damage_formula: Some("2d6 + 2"),
    },
    EntityBlueprint {
        id: "srd_ogre",
        name: "Ogre",
        category: "monster",
        keywords: &["Ogre", "Large giant"],
        default_cr: Some("2"),
        ac: Some(11),
        hp: Some(59),
        speed: Some("40 ft."),
        stats: Some(AbilityScores {
            str: 19,
            dex: 8,
            con: 16,
            int: 5,
            wis: 7,
            cha: 7,
        }),
        attack_bonus: Some(6),
        damage_formula: Some("2d8 + 4"),
    },
    EntityBlueprint {
        id: "srd_owlbear",
        name: "Owlbear",
        category: "monster",
        keywords: &["Owlbear", "Large monstrosity"],
        default_cr: Some("3"),
        ac: Some(13),
        hp: Some(59),
        speed: Some("40 ft."),
        stats: Some(AbilityScores {
            str: 20,
            dex: 12,
            con: 17,
            int: 3,
            wis: 12,
            cha: 7,
        }),
        attack_bonus: Some(7),
        damage_formula: Some("2d8 + 5"),
    },
    EntityBlueprint {
        id: "srd_minotaur",
        name: "Minotaur",
        category: "monster",
        keywords: &["Minotaur", "Large monstrosity"],
        default_cr: Some("3"),
        ac: Some(14),
        hp: Some(76),
        speed: Some("40 ft."),
        stats: Some(AbilityScores {
            str: 18,
            dex: 11,
            con: 16,
            int: 6,
            wis: 16,
            cha: 9,
        }),
        attack_bonus: Some(6),
        damage_formula: Some("2d12 + 4"),
    },
    EntityBlueprint {
        id: "srd_troll",
        name: "Troll",
        category: "monster",
        keywords: &["Troll", "Large giant"],
        default_cr: Some("5"),
        ac: Some(15),
        hp: Some(84),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 18,
            dex: 13,
            con: 20,
            int: 7,
            wis: 9,
            cha: 7,
        }),
        attack_bonus: Some(7),
        damage_formula: Some("2d6 + 4"),
    },
    EntityBlueprint {
        id: "srd_gelatinous_cube",
        name: "Gelatinous Cube",
        category: "monster",
        keywords: &["Gelatinous Cube", "Large ooze"],
        default_cr: Some("2"),
        ac: Some(6),
        hp: Some(84),
        speed: Some("15 ft."),
        stats: Some(AbilityScores {
            str: 14,
            dex: 3,
            con: 20,
            int: 1,
            wis: 6,
            cha: 1,
        }),
        attack_bonus: Some(4),
        damage_formula: Some("3d6"),
    },
    EntityBlueprint {
        id: "srd_adult_red_dragon",
        name: "Adult Red Dragon",
        category: "monster",
        keywords: &["Adult Red Dragon", "Huge dragon"],
        default_cr: Some("17"),
        ac: Some(19),
        hp: Some(256),
        speed: Some("40 ft., climb 40 ft., fly 80 ft."),
        stats: Some(AbilityScores {
            str: 27,
            dex: 10,
            con: 25,
            int: 16,
            wis: 13,
            cha: 21,
        }),
        attack_bonus: Some(14),
        damage_formula: Some("2d10 + 8"),
    },
    EntityBlueprint {
        id: "srd_lich",
        name: "Lich",
        category: "monster",
        keywords: &["Lich", "Medium undead"],
        default_cr: Some("21"),
        ac: Some(17),
        hp: Some(135),
        speed: Some("30 ft."),
        stats: Some(AbilityScores {
            str: 11,
            dex: 16,
            con: 16,
            int: 20,
            wis: 14,
            cha: 16,
        }),
        attack_bonus: Some(12),
        damage_formula: Some("3d6"),
    },
    // ── Spells ───────────────────────────────────────────────────────────────
    EntityBlueprint {
        id: "srd_spell_fireball",
        name: "Fireball",
        category: "spell",
        keywords: &["Fireball", "3rd-level evocation"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: Some("8d6"),
    },
    EntityBlueprint {
        id: "srd_spell_magic_missile",
        name: "Magic Missile",
        category: "spell",
        keywords: &["Magic Missile", "1st-level evocation"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: Some("1d4 + 1"),
    },
    EntityBlueprint {
        id: "srd_spell_cure_wounds",
        name: "Cure Wounds",
        category: "spell",
        keywords: &["Cure Wounds", "1st-level evocation"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: Some("1d8"),
    },
    EntityBlueprint {
        id: "srd_spell_healing_word",
        name: "Healing Word",
        category: "spell",
        keywords: &["Healing Word", "1st-level evocation"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: Some("1d4"),
    },
    EntityBlueprint {
        id: "srd_spell_eldritch_blast",
        name: "Eldritch Blast",
        category: "spell",
        keywords: &["Eldritch Blast", "Evocation cantrip"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: Some("1d10"),
    },
    // ── Magic Items ──────────────────────────────────────────────────────────
    EntityBlueprint {
        id: "srd_item_bag_of_holding",
        name: "Bag of Holding",
        category: "magic_item",
        keywords: &["Bag of Holding", "Wondrous item, uncommon"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: None,
    },
    EntityBlueprint {
        id: "srd_item_potion_of_healing",
        name: "Potion of Healing",
        category: "magic_item",
        keywords: &["Potion of Healing", "Potion, common"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: Some("2d4 + 2"),
    },
    EntityBlueprint {
        id: "srd_item_cloak_of_protection",
        name: "Cloak of Protection",
        category: "magic_item",
        keywords: &["Cloak of Protection", "Wondrous item, uncommon"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: None,
        damage_formula: None,
    },
    EntityBlueprint {
        id: "srd_item_longsword_plus_1",
        name: "Longsword +1",
        category: "magic_item",
        keywords: &["Longsword, +1", "Weapon (longsword), uncommon"],
        default_cr: None,
        ac: None,
        hp: None,
        speed: None,
        stats: None,
        attack_bonus: Some(1),
        damage_formula: Some("1d8 + 1"),
    },
];

pub fn get_blueprint_catalog() -> &'static [EntityBlueprint] {
    BLUEPRINT_CATALOG
}

pub fn find_blueprint_by_id(id: &str) -> Option<&'static EntityBlueprint> {
    BLUEPRINT_CATALOG.iter().find(|bp| bp.id == id)
}

pub fn find_blueprint_by_name(name: &str) -> Option<&'static EntityBlueprint> {
    let lower_name = name.to_lowercase();
    BLUEPRINT_CATALOG
        .iter()
        .find(|bp| bp.name.to_lowercase() == lower_name)
}

/// Identifies blueprints mentioned in a text block by matching entity names and keywords.
pub fn match_blueprints_in_text(text: &str) -> Vec<&'static EntityBlueprint> {
    let lower = text.to_lowercase();
    BLUEPRINT_CATALOG
        .iter()
        .filter(|bp| {
            if lower.contains(&bp.name.to_lowercase()) {
                return true;
            }
            bp.keywords
                .iter()
                .any(|kw| lower.contains(&kw.to_lowercase()))
        })
        .collect()
}
